# Generated by Django 6.0.2 on 2026-02-05 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapeta', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('HEMBRA', 'Hembra'), ('MACHO', 'Macho')], default='HEMBRA', max_length=10)),
                ('padre_nombre', models.CharField(help_text='Nombre del toro (finca o inseminación)', max_length=100)),
                ('estado_actual', models.CharField(choices=[('TERNERA', 'Ternera'), ('NOVILLA', 'Novilla'), ('VACA_PRODUCCION', 'Vaca en producción'), ('SECA', 'Vaca seca'), ('DESCARTADA', 'Descartada')], default='TERNERA', max_length=20)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('madre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crias', to='animals.animal')),
            ],
        ),
    ]
