# Generated by Django 6.0.2 on 2026-02-05 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reproduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evento', models.DateField()),
                ('toro', models.CharField(help_text='Nombre del toro (finca o inseminación)', max_length=100)),
                ('estado', models.CharField(choices=[('PRENADA', 'Preñada'), ('VACIA', 'Vacía'), ('OBSERVACION', 'Observación')], max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproducciones', to='animals.animal')),
            ],
        ),
    ]
