# Generated by Django 6.0.2 on 2026-02-05 22:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_reproduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='reproduction',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reproduction',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reproduction',
            name='type',
            field=models.CharField(choices=[('inseminacion', 'Inseminación'), ('monta', 'Monta natural'), ('diagnostico', 'Diagnóstico')], default='inseminacion', max_length=50),
        ),
    ]
