# Generated by Django 6.0.2 on 2026-02-05 22:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0003_reproduction_date_reproduction_notes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reproduction',
            old_name='type',
            new_name='tipo',
        ),
        migrations.RemoveField(
            model_name='reproduction',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reproduction',
            name='notes',
        ),
        migrations.AlterField(
            model_name='reproduction',
            name='fecha_evento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
