# Generated by Django 6.0.2 on 2026-02-06 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0004_rename_type_reproduction_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reproduction',
            name='estado',
            field=models.CharField(blank=True, choices=[('PRENADA', 'Preñada'), ('VACIA', 'Vacía'), ('OBSERVACION', 'Observación')], max_length=20, null=True),
        ),
    ]
