# Generated by Django 6.0.2 on 2026-02-06 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0005_alter_reproduction_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reproduction',
            name='toro',
            field=models.CharField(blank=True, help_text='Nombre del toro (finca o inseminación)', max_length=100, null=True),
        ),
    ]
