# Generated by Django 6.0.2 on 2026-02-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0006_alter_reproduction_toro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reproduction',
            name='tipo',
            field=models.CharField(choices=[('inseminacion', 'Inseminación'), ('monta', 'Monta natural')], default='inseminacion', max_length=50),
        ),
    ]
