# Generated by Django 6.0.2 on 2026-02-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0007_alter_reproduction_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reproduction',
            name='estado',
            field=models.CharField(blank=True, choices=[('PRENADA', 'Preñada'), ('VACIA', 'Vacía')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reproduction',
            name='tipo',
            field=models.CharField(choices=[('inseminacion', 'Inseminación'), ('monta', 'Monta natural'), ('diagnostico', 'Diagnóstico')], default='inseminacion', max_length=50),
        ),
    ]
