# Generated by Django 6.0.2 on 2026-02-11 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0008_alter_reproduction_estado_alter_reproduction_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reproduction',
            name='tipo',
            field=models.CharField(choices=[('inseminacion', 'Inseminación'), ('monta', 'Monta natural'), ('diagnostico', 'Diagnóstico'), ('parto', 'Parto')], default='inseminacion', max_length=50),
        ),
    ]
