# Generated by Django 6.0.2 on 2026-02-11 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0009_alter_reproduction_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='reproduction',
            name='sexo_cria',
            field=models.CharField(blank=True, choices=[('hembra', 'Hembra'), ('macho', 'Macho')], max_length=10, null=True),
        ),
    ]
